/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Claims {
  aud: Array<string>
  iss: string
  sub: string
  email?: string
  exp: number
}
export class JwtService {
  constructor(kid: string, privateKeyPem: string)
  generateToken(claim: Claims): string
}
